import sys

def translate(html):
    r = [
        # Title & meta
        ('<title>Auditoría | Plataforma Inteligente de Auditoría</title>', '<title>Audit | Intelligent Audit Platform</title>'),
        ('lang="es"', 'lang="en"'),
        # Auth modal tabs
        ('Iniciar Sesión\n                    </button>', 'Sign In\n                    </button>'),
        ('Registrarse\n                    </button>', 'Register\n                    </button>'),
        # Login
        ('Bienvenido de nuevo</h2>', 'Welcome Back</h2>'),
        ('placeholder="Contraseña"', 'placeholder="Password"'),
        ('>Entrar\n                        </button>', '>Sign In\n                        </button>'),
        ('>o continúa con<', '>or continue with<'),
        ('>Continuar con Google\n                    </button>', '>Continue with Google\n                    </button>'),
        # Register
        ('Crear cuenta</h2>', 'Create Account</h2>'),
        ('placeholder="Nombre o alias"', 'placeholder="Name or alias"'),
        ('placeholder="Contraseña (mín. 6 caracteres)"', 'placeholder="Password (min. 6 characters)"'),
        ('>Crear cuenta\n                        </button>', '>Create Account\n                        </button>'),
        # Hero
        ('Auditoría de <br /><span class="text-emerald-400 drop-shadow-lg">Impacto Multicriterio</span>',
         'Multicriterion <br /><span class="text-emerald-400 drop-shadow-lg">Impact Audit</span>'),
        ('Cuantifica el impacto Económico, Social y Ambiental de tu cadena de suministro agroalimentaria en\n                    segundos.',
         'Quantify the Economic, Social and Environmental impact of your agri-food supply chain in seconds.'),
        ('Comenzar Análisis <span class="text-2xl', 'Begin Analysis <span class="text-2xl'),
        # Phase 2
        ('Seleccione su Entorno de Trabajo\n                        </h2>', 'Select Your Working Environment\n                        </h2>'),
        ('Configure los parámetros de auditoría para su sesión actual.', 'Configure the audit parameters for your current session.'),
        ('<h3 class="text-2xl font-bold mb-3">Entorno de Simulación</h3>', '<h3 class="text-2xl font-bold mb-3">Simulation Environment</h3>'),
        ('Proyecciones logísticas e inventarios avanzados para la\n                    toma de decisiones estratégicas.',
         'Logistical projections and advanced inventories for strategic decision-making.'),
        ('>Acceder\n                a Simulación</button>', '>Access Simulation</button>'),
        ('<h3 class="text-2xl font-bold mb-3">Base de Datos Global</h3>', '<h3 class="text-2xl font-bold mb-3">Global Database</h3>'),
        ('Gestión de perfiles institucionales y calibración de\n                    coeficientes técnicos internacionales.',
         'Management of institutional profiles and calibration of international technical coefficients.'),
        ('>Gestionar\n                                Datos</button>', '>Manage Data</button>'),
        ('© 2026 Grupo de\n                Investigación SoGReS-MF · Universitat Jaume I', '© 2026 SoGReS-MF Research Group · Universitat Jaume I'),
        # Admin panel
        ('<h2>Panel de Administración Global</h2>', '<h2>Global Administration Panel</h2>'),
        ('Parámetros sincronizados en tiempo real mediante base de datos NoSQL.', 'Parameters synchronised in real time via NoSQL database.'),
        ('>Salir al Menú</button>', '>Back to Menu</button>'),
        ('>Subir a la Nube</button>', '>Upload to Cloud</button>'),
        ('<span>👨‍🔧 Catálogo de Perfiles\n                        Laborales</span>', '<span>👨‍🔧 Labour Profile Catalogue</span>'),
        ('placeholder="🔍 Buscar perfil..."', 'placeholder="🔍 Search profile..."'),
        ('<th>Descripción del Rol</th>', '<th>Role Description</th>'),
        ('<th>Asociar a Tecnología</th>', '<th>Associate with Technology</th>'),
        ('<th>Horas Base / Día</th>', '<th>Base Hours / Day</th>'),
        ('<th>Tarifa Estándar (€/hora)</th>', '<th>Standard Rate (€/hour)</th>'),
        ('>+ Añadir Nuevo Perfil</button>', '>+ Add New Profile</button>'),
        ('<span>🍎 Base de Datos de Materia\n                        Prima (Frutas)</span>', '<span>🍎 Raw Material Database (Fruit)</span>'),
        ('placeholder="🔍 Buscar materia prima..."', 'placeholder="🔍 Search raw material..."'),
        ('<th>Especie / Lote</th>', '<th>Species / Batch</th>'),
        ('<th>Impacto Ambiental (µPt/kg)</th>', '<th>Environmental Impact (µPt/kg)</th>'),
        ('<th>Impacto Social (Pt/kg)</th>', '<th>Social Impact (Pt/kg)</th>'),
        ('<th>Valor Comercial (€/kg)</th>', '<th>Commercial Value (€/kg)</th>'),
        ('>+ Añadir Nueva Especie</button>', '>+ Add New Species</button>'),
        ('<span>⚡ Catálogo de Soluciones\n                        Tecnológicas Fijas</span>', '<span>⚡ Fixed Technology Solutions Catalogue</span>'),
        ('placeholder="🔍 Buscar tecnología..."', 'placeholder="🔍 Search technology..."'),
        ('<th>Identificador del Equipo</th>', '<th>Equipment Identifier</th>'),
        ('<th>Carga Ambiental (µPt)</th>', '<th>Environmental Load (µPt)</th>'),
        ('<th>Carga Social (Pt)</th>', '<th>Social Load (Pt)</th>'),
        ('<th>Coste Operativo (€)</th>', '<th>Operating Cost (€)</th>'),
        ('>+ Añadir Nuevo Equipo</button>', '>+ Add New Equipment</button>'),
        ('<span>📦 Catálogo de Materiales de\n                        Envasado</span>', '<span>📦 Packaging Materials Catalogue</span>'),
        ('placeholder="🔍 Buscar material..."', 'placeholder="🔍 Search material..."'),
        ('<th>Identificador del Material</th>', '<th>Material Identifier</th>'),
        ('<th>Carga Ambiental (µPt/ud)</th>', '<th>Environmental Load (µPt/unit)</th>'),
        ('<th>Carga Social (Pt/ud)</th>', '<th>Social Load (Pt/unit)</th>'),
        ('<th>Coste Unitario (€/ud)</th>', '<th>Unit Cost (€/unit)</th>'),
        ('>+ Añadir Nuevo Material</button>', '>+ Add New Material</button>'),
        # Nav brand
        ('<span class="font-extrabold text-slate-900 text-lg tracking-tight">Auditoría</span>',
         '<span class="font-extrabold text-slate-900 text-lg tracking-tight">Audit</span>'),
        # Nav tabs
        ('>Comparativa Directa\n                </button>', '>Direct Comparison\n                </button>'),
        ('>Escalabilidad\n                </button>', '>Scalability\n                </button>'),
        ('>Comp. Indirecta\n                </button>', '>Indirect Comp.\n                </button>'),
        ('<span class="hidden sm:inline">Archivo </span>Nube', '<span class="hidden sm:inline">Cloud </span>Archive'),
        ('title="Guardar"', 'title="Save"'),
        ('title="Cargar"', 'title="Load"'),
        ('title="Borrar"', 'title="Clear"'),
        # Historial section
        ('>Registro Cloud\n                            </h1>', '>Cloud Archive\n                            </h1>'),
        ('Acceda a los\n                            informes previamente calculados y sincronizados.',
         'Access previously calculated and synchronised reports.'),
        ('>Purgar Base de Datos</button>', '>Purge Database</button>'),
        # Indirect comparison HTML
        ('<h1 class="text-2xl font-bold tracking-tight text-slate-900">Comparativa Indirecta</h1>',
         '<h1 class="text-2xl font-bold tracking-tight text-slate-900">Indirect Comparison</h1>'),
        ('Evalúa simulaciones de auditoría\n                    frente a vectores ESG y benchmarks multicriterio.',
         'Evaluate audit simulations against ESG vectors and multicriterion benchmarks.'),
        ('>Comparar seleccionadas\n                                </button>', '>Compare selected\n                                </button>'),
        ('>Borrar todo\n                                </button>', '>Delete all\n                                </button>'),
        ('>Simulaciones\n                                guardadas</span>', '>Saved simulations</span>'),
        ('>Seleccionar\n                                todas</button>', '>Select all</button>'),
        ('<h3 class="text-[10px] font-bold uppercase tracking-widest text-slate-500">Tabla\n                                            Comparativa</h3>',
         '<h3 class="text-[10px] font-bold uppercase tracking-widest text-slate-500">Comparative Table</h3>'),
        ('<p class="text-[11px] text-slate-400 mt-0.5">Desperdicio vs Punto de Equilibrio\n                                            · Impacto ESG</p>',
         '<p class="text-[11px] text-slate-400 mt-0.5">Waste vs Break-even Point · ESG Impact</p>'),
        ('<h3 class="text-xs font-bold uppercase tracking-widest text-slate-500">Pérdida\n                                            Base vs Vectores ESG</h3>',
         '<h3 class="text-xs font-bold uppercase tracking-widest text-slate-500">Base Loss vs ESG Vectors</h3>'),
        ('<p class="text-xs text-slate-400 mt-0.5">Punto de equilibrio por simulación</p>',
         '<p class="text-xs text-slate-400 mt-0.5">Break-even point per simulation</p>'),
        ('<h3 class="text-xs font-bold uppercase tracking-widest text-slate-500">Perfil\n                                            ESG Comparativo</h3>',
         '<h3 class="text-xs font-bold uppercase tracking-widest text-slate-500">Comparative ESG Profile</h3>'),
        ('<p class="text-xs text-slate-400 mt-0.5">Vectores Ambiental · Social · Económico\n                                        </p>',
         '<p class="text-xs text-slate-400 mt-0.5">Environmental · Social · Economic Vectors</p>'),
        # Section 22 HTML
        ('>Auditoría\n                                Comparativa de Mercado</h2>', '>Market Comparative Audit</h2>'),
        ('Configure su inventario\n                                y las tecnologías a evaluar para el cálculo de sostenibilidad y eficiencia energética.',
         'Configure your inventory and the technologies to be evaluated for sustainability and energy efficiency calculations.'),
        ('>I. Matriz de Inventario\n                                </h3>', '>I. Inventory Matrix</h3>'),
        ('>Añadir Producto Manual\n                                    </button>', '>Add Product Manually\n                                    </button>'),
        ('>Subir Archivo CSV\n                                    </button>', '>Upload CSV File\n                                    </button>'),
        ('>II. Solución Tecnológica\n                                </h3>', '>II. Technological Solution</h3>'),
        ('>Añadir Equipo a Evaluar\n                                    </button>', '>Add Equipment to Evaluate\n                                    </button>'),
        ('>+ Perfil Independiente\n                                    </button>', '>+ Independent Profile\n                                    </button>'),
        ('>Ejecutar Simulación\n                                <svg', '>Run Simulation\n                                <svg'),
        # Section 23 HTML
        ('>Proyección de\n                                Escalabilidad</h1>', '>Scalability Projection</h1>'),
        ('Analice la\n                                viabilidad ambiental, social y financiera a lo largo de una red de centros logísticos.',
         'Analyse the environmental, social and financial viability across a network of logistics centres.'),
        ('<h2 class="text-2xl font-bold text-slate-900">I. Tecnología Base a Implementar</h2>',
         '<h2 class="text-2xl font-bold text-slate-900">I. Base Technology to Implement</h2>'),
        ('>Añadir Equipo a Evaluar\n                                </button>', '>Add Equipment to Evaluate\n                                </button>'),
        ('>+ Perfil Independiente\n                                </button>', '>+ Independent Profile\n                                </button>'),
        ('<h2 class="text-2xl font-bold text-slate-900">II. Nodos de la Cadena de Suministro</h2>',
         '<h2 class="text-2xl font-bold text-slate-900">II. Supply Chain Nodes</h2>'),
        ('> Crear Nuevo Centro Logístico</button>', '> Create New Logistics Centre</button>'),
        ('><span class="tracking-wider uppercase">Proyectar Red Logística</span>', '><span class="tracking-wider uppercase">Project Logistics Network</span>'),
        # Modals HTML
        ('>Acceso Restringido</h2>', '>Restricted Access</h2>'),
        ('Por favor, introduce la clave de\n                administrador para continuar.',
         'Please enter the administrator key to continue.'),
        ('>Cancelar</button>', '>Cancel</button>'),
        ('>Autorizar</button>', '>Authorise</button>'),
        ('<h3 class="text-lg font-bold text-slate-900">Seleccionar Variedad</h3>',
         '<h3 class="text-lg font-bold text-slate-900">Select Variety</h3>'),
        ('placeholder="Buscar por nombre... (ej: Apple, Lemon)"', 'placeholder="Search by name... (e.g. Apple, Lemon)"'),
        ('<span id="contador-frutas">Catálogo de la A → Z</span>', '<span id="contador-frutas">Catalogue A → Z</span>'),
        ('<h3 class="text-lg font-bold text-slate-900">Seleccionar Perfil Laboral</h3>',
         '<h3 class="text-lg font-bold text-slate-900">Select Labour Profile</h3>'),
        ('placeholder="Buscar operario o rol..."', 'placeholder="Search operator or role..."'),
        ('<span id="contador-mant">Catálogo de Perfiles</span>', '<span id="contador-mant">Profile Catalogue</span>'),
        # Back button
        ('>←</span> Volver a Parámetros\n                    </button>', '>←</span> Back to Parameters\n                    </button>'),
        # Loader texts JS
        ('"Iniciando motor matemático..."', '"Initialising mathematical engine..."'),
        ('"Despertando servidor en la nube (puede tardar unos segundos)..."', '"Waking up cloud server (this may take a few seconds)..."'),
        ('"Calculando proyecciones de merma..."', '"Calculating waste projections..."'),
        ('"Sincronizando con SoGReS Cloud..."', '"Synchronising with SoGReS Cloud..."'),
        ('"Generando dictamen visual..."', '"Generating visual report..."'),
        # JS confirm dialogs
        ("confirm('¿Cerrar sesión?')", "confirm('Sign out?')"),
        ('confirm("⚠️ ATENCIÓN: Esta acción eliminará permanentemente la trazabilidad. ¿Proceder?")',
         'confirm("⚠️ WARNING: This action will permanently delete all traceability records. Proceed?")'),
        ('confirm("¿Restaurar valores fábrica?")', 'confirm("Restore factory values?")'),
        ('"¿Estás seguro de que quieres borrar todos los datos actuales y empezar una simulación en blanco?"',
         '"Are you sure you want to clear all current data and start a blank simulation?"'),
        ("confirm('¿Eliminar todas las simulaciones guardadas?')", "confirm('Delete all saved simulations?')"),
        # JS error strings
        ("errEl.textContent = 'Email o contraseña incorrectos'", "errEl.textContent = 'Incorrect email or password'"),
        ("errEl.textContent = 'Introduce un nombre válido'", "errEl.textContent = 'Please enter a valid name'"),
        ("errEl.textContent = e.code === 'auth/email-already-in-use' ? 'Este email ya está registrado' : 'Error al crear la cuenta'",
         "errEl.textContent = e.code === 'auth/email-already-in-use' ? 'This email is already registered' : 'Error creating account'"),
        # JS notifications
        ("window.showNotification('Añade al menos una fruta al inventario', 'warning')",
         "window.showNotification('Add at least one fruit to the inventory', 'warning')"),
        ("window.showNotification('Añade al menos una tecnología a evaluar', 'warning')",
         "window.showNotification('Add at least one technology to evaluate', 'warning')"),
        ("window.showNotification('Elige la fuente de datos en todas las máquinas', 'error')",
         "window.showNotification('Select the data source for all machines', 'error')"),
        ("window.showNotification('Error del servidor: '", "window.showNotification('Server error: '"),
        ("window.showNotification('El volumen total de stock debe ser mayor a 0 kg', 'error')",
         "window.showNotification('Total stock volume must be greater than 0 kg', 'error')"),
        ("window.showNotification('Añade al menos una tecnología o perfil', 'error')",
         "window.showNotification('Add at least one technology or profile', 'error')"),
        ("window.showNotification('Crea al menos un almacén logístico', 'warning')",
         "window.showNotification('Create at least one logistics centre', 'warning')"),
        ('window.showNotification("Error de conexión. Asegúrate de que el Backend está encendido.", "error")',
         'window.showNotification("Connection error. Please ensure the backend is running.", "error")'),
        ('window.showNotification("Datos cargados en el simulador.")', 'window.showNotification("Data loaded into the simulator.")'),
        ('window.showNotification("Borrador guardado localmente.")', 'window.showNotification("Draft saved locally.")'),
        ('window.showNotification("Entorno reseteado correctamente.")', 'window.showNotification("Environment reset successfully.")'),
        ("window.showNotification('☁️ BBDD Guardada Correctamente')", "window.showNotification('☁️ Database Saved Successfully')"),
        ("window.showNotification('Error Firebase', 'error')", "window.showNotification('Firebase Error', 'error')"),
        ("window.showNotification('Restaurado')", "window.showNotification('Restored')"),
        ('window.showNotification("🗑️ Registro Limpiado.")', 'window.showNotification("🗑️ Records Cleared.")'),
        ("window.showNotification('No hay datos para exportar.', 'warning')", "window.showNotification('No data to export.', 'warning')"),
        ("window.showNotification('Preparando informe... En la ventana de impresión, selecciona \"Guardar como PDF\".'",
         "window.showNotification('Preparing report... In the print window, select \"Save as PDF\".'"),
        ('window.showNotification("DataSets Inyectados.")', 'window.showNotification("Datasets Injected.")'),
        ('window.showNotification("Clave denegada.", "error")', 'window.showNotification("Key denied.", "error")'),
        ('window.showNotification("Contraseña incorrecta", "error")', 'window.showNotification("Incorrect password", "error")'),
        ('window.showNotification("Error de conexión con el servidor", "error")', 'window.showNotification("Connection error with server", "error")'),
        ("window.showNotification('✅ Simulación guardada en la nube')", "window.showNotification('✅ Simulation saved to cloud')"),
        ("window.showNotification('Error al guardar', 'error')", "window.showNotification('Error saving', 'error')"),
        ("window.showNotification('🔄 Regenerando simulación...')", "window.showNotification('🔄 Regenerating simulation...')"),
        ("window.showNotification('No hay suficientes datos para regenerar', 'warning')",
         "window.showNotification('Insufficient data to regenerate', 'warning')"),
        ("window.showNotification('✅ Nombre actualizado')", "window.showNotification('✅ Name updated')"),
        ("window.showNotification('Selecciona al menos 2 simulaciones para comparar', 'warning')",
         "window.showNotification('Select at least 2 simulations to compare', 'warning')"),
        ("window.showNotification('⚠️ No hay ningún borrador guardado en este dispositivo.', 'warning')",
         "window.showNotification('⚠️ No draft saved on this device.', 'warning')"),
        ('window.showNotification("Error al leer el borrador.", "error")', 'window.showNotification("Error reading the draft.", "error")'),
        ('window.showNotification("Borrador cargado con éxito.")', 'window.showNotification("Draft loaded successfully.")'),
        ("window.showNotification('Primero ejecuta una simulación en Comparativa Directa o Escalabilidad', 'warning')",
         "window.showNotification('First run a simulation in Direct Comparison or Scalability', 'warning')"),
        # JS template strings - fruit form
        ('"Variedad Orgánica"', '"Organic Variety"'),
        ('"Seleccionar variedad..."', '"Select variety..."'),
        ('"Volumen (kg)"', '"Volume (kg)"'),
        ('"Merma (%)"', '"Waste (%)"'),
        ('title="Eliminar lote"', 'title="Delete batch"'),
        # getMantRowHTML
        ('"Cantidad de operarios"', '"Number of operators"'),
        ('"Horas dedicadas (Editable)"', '"Hours allocated (Editable)"'),
        ('"Coste por hora en € (Fijado en Base de Datos Global)"', '"Cost per hour in € (Fixed in Global Database)"'),
        ('"Seleccionar perfil..."', '"Select profile..."'),
        ('"+ Asignar Operario"', '"+ Assign Operator"'),
        ('title="Quitar operario"', 'title="Remove operator"'),
        # getMaquinaTemplate labels
        ('"Solución Tecnológica"', '"Technological Solution"'),
        ('"-- Seleccionar Tecnología --"', '"-- Select Technology --"'),
        ('"Alias del Equipo"', '"Equipment Alias"'),
        ('"Ej: Sistema de Nebulización Z1"', '"E.g.: Nebulisation System Z1"'),
        ('"Cantidad de Material"', '"Material Quantity"'),
        ('"Unidades o medida a utilizar"', '"Units or measure to use"'),
        ('"Cantidad (uds / cm / m)"', '"Quantity (units / cm / m)"'),
        ('"Coste unitario (€/ud) — de la BBDD"', '"Unit cost (€/unit) — from DB"'),
        ('"Coste Total Estimado"', '"Estimated Total Cost"'),
        ('"Film de Envasado"', '"Packaging Film"'),
        ('"Complemento opcional para la bandeja"', '"Optional complement for the tray"'),
        ('"Añadir Film"', '"Add Film"'),
        ('"Quitar Film"', '"Remove Film"'),
        ('"Tipo de Film"', '"Film Type"'),
        ('"-- Seleccionar --"', '"-- Select --"'),
        ('"Coste Film Estimado"', '"Estimated Film Cost"'),
        ('"Operador de Producción"', '"Production Operator"'),
        ('"Mano de obra asociada al envasado"', '"Labour associated with packaging"'),
        ('"Añadir Operador"', '"Add Operator"'),
        ('"Quitar Operador"', '"Remove Operator"'),
        ('"Perfil Laboral"', '"Labour Profile"'),
        ('"Operarios"', '"Operators"'),
        ('"Horas / día"', '"Hours / day"'),
        ('"Coste Operador Estimado"', '"Estimated Operator Cost"'),
        ('"Sistema"', '"System"'),
        ('"Hardware"', '"Hardware"'),
        ('"Potencia (kW)"', '"Power (kW)"'),
        ('"Horas / día (h)"', '"Hours / day (h)"'),
        ('"Boquillas (uds)"', '"Nozzles (units)"'),
        ('"Caudal / boquilla (L/h)"', '"Flow rate / nozzle (L/h)"'),
        ('"Tratamiento Químico"', '"Chemical Treatment"'),
        ('"Opcional"', '"Optional"'),
        ('"Inyección de lejía"', '"Bleach Injection"'),
        ('"Desactivado · sin aditivo químico"', '"Deactivated · no chemical additive"'),
        ('"Activado · Inyectando aditivo"', '"Activated · Injecting additive"'),
        ('"Concentración (g/L)"', '"Concentration (g/L)"'),
        ('"Consumo Agua"', '"Water Consumption"'),
        ('"Cálculo automático"', '"Automatic calculation"'),
        ('"Fórmula Aplicada"', '"Applied Formula"'),
        ('"Nº Boquillas"', '"No. Nozzles"'),
        ('"Caudal (L/h)"', '"Flow rate (L/h)"'),
        ('"Horas/Día"', '"Hours/Day"'),
        ('"Resultado estimado"', '"Estimated result"'),
        ('"Mantenimiento"', '"Maintenance"'),
        ('"Intervención humana"', '"Human intervention"'),
        ('"Perfil Técnico"', '"Technical Profile"'),
        ('"Cant."', '"Qty."'),
        ('"Horas"', '"Hours"'),
        # getPersonalTemplate
        ('"Nombre de la Estrategia (Alias)"', '"Strategy Name (Alias)"'),
        ('"Ej: Refuerzo de Selección Manual"', '"E.g.: Manual Selection Reinforcement"'),
        ('value="Solución RRHH ${num}"', 'value="HR Solution ${num}"'),
        ('"Perfil Seleccionado"', '"Selected Profile"'),
        # addAlmacen
        ('`🏢 Centro Logístico ${num}`', '`🏢 Logistics Centre ${num}`'),
        ('"+ Añadir Lote Manual"', '"+ Add Batch Manually"'),
        ('"📊 Importar CSV a este almacén"', '"📊 Import CSV to this centre"'),
        ("'▼ OCULTAR'", "'▼ HIDE'"),
        ("'▶ MOSTRAR'", "'▶ SHOW'"),
        ("icon.innerText = '▼ OCULTAR'", "icon.innerText = '▼ HIDE'"),
        ("icon.innerText = '▶ MOSTRAR'", "icon.innerText = '▶ SHOW'"),
        # importarCSV
        ('`Éxito: ${count} lotes importados.`', '`Success: ${count} batches imported.`'),
        ('`Error: CSV incorrecto.`', '`Error: Invalid CSV.`'),
        # renderizarHistorial
        ("'El archivo seguro se encuentra vacío.'", "'The secure archive is empty.'"),
        ('`Auditoría: ${escapeHTML(h.fecha)}`', '`Audit: ${escapeHTML(h.fecha)}`'),
        ("'Cargar Simulación'", "'Load Simulation'"),
        # getMantRowHTML placeholder
        ("{ desc: 'Cargando...', h: 0, p: 0 }", "{ desc: 'Loading...', h: 0, p: 0 }"),
        # getTechOptions / getMantOptions
        ("'Sin perfiles creados'", "'No profiles created'"),
        ("'Ninguna (General)'", "'None (General)'"),
        ("'Equipos'", "'Equipment'"),
        ("'Material de Envasado'", "'Packaging Material'"),
        # addFilaGestor
        ('"Ej: Nuevo elemento"', '"E.g.: New element"'),
        ('"Ej: Técnico"', '"E.g.: Technician"'),
        ('>Mantén <b>Ctrl</b> para seleccionar varias<', '>Hold <b>Ctrl</b> to select multiple<'),
        # buildEscenario0Card JS strings
        ("'Producto Representativo del Lote'", "'Representative Product of the Batch'"),
        ("'Producto teórico que representa la media matemática ponderada de los impactos.'",
         "'Theoretical product representing the weighted mathematical average of the impacts.'"),
        ("'Dictamen de Inacción'", "'Inaction Assessment'"),
        ('Se degradarán <strong>${R0.total_desp.toFixed(2)} kg</strong> irremediablemente.',
         'Will be degraded <strong>${R0.total_desp.toFixed(2)} kg</strong> irretrievably.'),
        ("'Escenario Base'", "'Base Scenario'"),
        ("'Deuda Ambiental'", "'Environmental Debt'"),
        ("'Impacto ecotoxicológico.'", "'Ecotoxicological impact.'"),
        ("'Deuda Social'", "'Social Debt'"),
        ("'Impacto en salud humana.'", "'Impact on human health.'"),
        ("'Pérdida Financiera'", "'Financial Loss'"),
        ("'Valor monetario directo.'", "'Direct monetary value.'"),
        ("'Impacto de inacción:'", "'Impact of inaction:'"),
        ('Pérdida directa de <strong>${R0.total_desp.toFixed(2)} kg</strong> en su cadena de suministro actual si no se aplica tecnología.',
         'Direct loss of <strong>${R0.total_desp.toFixed(2)} kg</strong> in your current supply chain if no technology is applied.'),
        ("'Mide el impacto ecotoxicológico.'", "'Measures the ecotoxicological impact.'"),
        ("'Mide el impacto en la salud humana.'", "'Measures the impact on human health.'"),
        ('"Resultado de Evaluación"', '"Evaluation Result"'),
        ('"Cantidad Inicial"', '"Initial Quantity"'),
        ('"Desperdicio"', '"Waste"'),
        ('"Máximo Desperdicio Admisible"', '"Maximum Admissible Waste"'),
        ('"Reducción Equivalente Mínima"', '"Minimum Equivalent Reduction"'),
        ('" VECTOR LIMITANTE — "', '" LIMITING VECTOR — "'),
        ('"% del desperdicio"', '"% of waste"'),
        # buildMachineCard
        ("'<strong>Punto de Equilibrio:</strong>'", "'<strong>Break-even Point:</strong>'"),
        ("'Cantidad exacta de merma que la tecnología debe salvar para generar un impacto neto positivo.'",
         "'Exact amount of waste the technology must save to generate a net positive impact.'"),
        ("'<strong>Vector Limitante:</strong>'", "'<strong>Limiting Vector:</strong>'"),
        ("'La dimensión más exigente de compensar.'", "'The most demanding dimension to compensate.'"),
        ('<strong>✅ Viabilidad Confirmada:</strong> Escenario óptimo. Es suficiente con salvar el <strong>${percent.toFixed(1)}%</strong> del producto para superar el punto de equilibrio del sistema.',
         '<strong>✅ Viability Confirmed:</strong> Optimal scenario. Saving <strong>${percent.toFixed(1)}%</strong> of the product is sufficient to exceed the system\'s break-even point.'),
        ('<strong>⚠️ Veredicto Desfavorable:</strong> Tecnología sobredimensionada. La máquina contamina o cuesta más de lo que lograría salvar en este almacén.',
         '<strong>⚠️ Unfavourable Verdict:</strong> Oversized technology. The machine pollutes or costs more than it would save in this warehouse.'),
        ("'INVIABLE'", "'NOT VIABLE'"),
        ('"📊 Desglose de Merma vs Exigencia por Producto"', '"📊 Waste vs Requirement Breakdown by Product"'),
        ('"Perfil Tridimensional de Exigencia (ESG)"', '"Three-dimensional Requirement Profile (ESG)"'),
        # Charts labels
        ("'Kilos exigidos para rentabilidad'", "'Kilos required for profitability'"),
        ("'Kilos (kg)'", "'Kilos (kg)'"),
        ("'Pérdida Base (kg)'", "'Base Loss (kg)'"),
        ("'Kilos a Salvar (Objetivo)'", "'Kilos to Save (Target)'"),
        ("'Merma Proyectada'", "'Projected Waste'"),
        ("'🌿 Ambiental'", "'🌿 Environmental'"),
        ("'👥 Social'", "'👥 Social'"),
        ("'💶 Económico'", "'💶 Economic'"),
        # Radar labels in arrays
        ("labels: ['🌿 Ambiental', '👥 Social', '💶 Económico']",
         "labels: ['🌿 Environmental', '👥 Social', '💶 Economic']"),
        # Comparador strings
        ('"Comparador Tridimensional ESG"', '"Three-dimensional ESG Comparator"'),
        ('"Selecciona las soluciones que quieres superponer en el perfil de exigencia."',
         '"Select the solutions you wish to overlay on the requirement profile."'),
        ('"Seleccionar todas"', '"Select all"'),
        ('"Selecciona al menos 2 soluciones para comparar"', '"Select at least 2 solutions to compare"'),
        ('"Comparador entre Nodos Logísticos"', '"Comparator Between Logistics Nodes"'),
        ('"Selecciona los centros que quieres superponer en el perfil ESG."',
         '"Select the centres you wish to overlay on the ESG profile."'),
        ('"Seleccionar todos"', '"Select all"'),
        ('"Selecciona al menos 2 nodos para comparar"', '"Select at least 2 nodes to compare"'),
        # ejecutarOpcion22/23 dashboard strings
        ('Auditoría: Viabilidad de Mercado', 'Audit: Market Viability'),
        ('Evaluando ${mqs.length} modelos sobre un stock nominal de', 'Evaluating ${mqs.length} models on a nominal stock of'),
        ('Descargar Informe Oficial', 'Download Official Report'),
        ('Análisis de Viabilidad: Merma Actual vs. Kilos Mínimos a Salvar', 'Viability Analysis: Current Waste vs. Minimum Kilos to Save'),
        ('Auditoría: Escalabilidad Logística', 'Audit: Logistics Scalability'),
        ('Proyección descentralizada en', 'Decentralised projection across'),
        ('nodos geográficos', 'geographical nodes'),
        ('🏢 Matriz Logística ${idx + 1}', '🏢 Logistics Matrix ${idx + 1}'),
        ('No se ha detectado mercancía en esta ubicación.', 'No goods detected at this location.'),
        # regenerar strings
        ('Descargar Informe', 'Download Report'),
        ('Análisis de Viabilidad', 'Viability Analysis'),
        ('Proyección en', 'Projection across'),
        ('🏢 Matriz Logística ${i + 1}', '🏢 Logistics Matrix ${i + 1}'),
        ('Sin mercancía.', 'No goods.'),
        ('Error al calcular este nodo.', 'Error calculating this node.'),
        # renderizarIndirecta
        ('"¿Listo para comparar tus auditorías?"', '"Ready to compare your audits?"'),
        ('"Las simulaciones se guardan aquí automáticamente cada vez que ejecutas un análisis en Comparativa Directa o Escalabilidad."',
         '"Simulations are saved here automatically each time you run an analysis in Direct Comparison or Scalability."'),
        ("'📦 Escalabilidad'", "'📦 Scalability'"),
        ("'📊 Comp. Directa'", "'📊 Direct Comp.'"),
        ("'Punto de equilibrio'", "'Break-even point'"),
        ("'Desperdicio'", "'Waste'"),
        ("'Equilibrio'", "'Break-even'"),
        ("'Abrir'", "'Open'"),
        ("'Regenerar'", "'Regenerate'"),
        ("'Sin datos'", "'No data'"),
        ("'Viable'", "'Viable'"),
        ("'Inviable'", "'Not Viable'"),
        ("'cubierto'", "'covered'"),
        ("'Editar nombre'", "'Edit name'"),
        ("'kg desp.'", "'kg waste.'"),
        ('"Guardar"', '"Save"'),
        ('"Cancelar"', '"Cancel"'),
        # autoguardar
        ("window.autoguardarIndirecta('Comparativa Directa')", "window.autoguardarIndirecta('Direct Comparison')"),
        ("window.autoguardarIndirecta('Escalabilidad')", "window.autoguardarIndirecta('Scalability')"),
        # guardarHistorial types
        ('"Comparativa de Mercado"', '"Market Comparison"'),
        ('"Escalabilidad Logística"', '"Logistics Scalability"'),
        ('item.tipo === "Comparativa de Mercado"', 'item.tipo === "Market Comparison"'),
        # verResultadoIndirecto nav
        ('" de "', '" of "'),
        ('"simulaciones"', '"simulations"'),
        # Unused but safe
        ("'Simulación '", "'Simulation '"),
        # filtrarListaMant counter
        ("'Catálogo de Perfiles'", "'Profile Catalogue'"),
        ('`${count} coincidencias`', '`${count} matches`'),
        # filtrarListaFrutas counter
        ("'Catálogo de la A → Z'", "'Catalogue A → Z'"),
        # nombre edit buttons in renderizarIndirecta
        ('>Guardar</button>', '>Save</button>'),
        ('>Cancelar</button>', '>Cancel</button>'),
        # compararSeleccionadas table labels
        ('"Tabla Comparativa"', '"Comparative Table"'),
        ('"Desperdicio vs Punto de Equilibrio · Impacto ESG"', '"Waste vs Break-even Point · ESG Impact"'),
        ('"Pérdida Base vs Vectores ESG"', '"Base Loss vs ESG Vectors"'),
        ('"Punto de equilibrio por simulación"', '"Break-even point per simulation"'),
        ('"Perfil ESG Comparativo"', '"Comparative ESG Profile"'),
        ('"Vectores Ambiental · Social · Económico"', '"Environmental · Social · Economic Vectors"'),
        ('"Desperdicio"', '"Waste"'),
        ('"P. Equilibrio"', '"Break-even"'),
        ('"Vector Limitante"', '"Limiting Vector"'),
        ('"Ambiental"', '"Environmental"'),
        ('"Económico"', '"Economic"'),
        ('"% cubierto"', '"% covered"'),
        # verHistorial notification
        ('window.showNotification("Datos cargados en el simulador.")', 'window.showNotification("Data loaded into the simulator.")'),
        # borrar/limpiar already done above, but extra safety:
        ("'Error al guardar'", "'Error saving'"),
    ]
    count = 0
    for old, new in r:
        if old in html:
            html = html.replace(old, new)
            count += 1
    import sys
    print(f"Applied {count}/{len(r)} replacements", file=sys.stderr)
    return html

with open('/dev/stdin', 'r', encoding='utf-8') as f:
    content = f.read()

result = translate(content)

with open('/mnt/user-data/outputs/index_en.html', 'w', encoding='utf-8') as f:
    f.write(result)

print("Done")
